package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALL_CATEGORY_TOPICS".
 */
@Entity
public class AllCategoryTopics {
    private String Forum_topics_id;
    private String Forum_category_id;
    private String Topic_name;
    private String Created_on;
    private String Created_by;
    private String Total_comments;
    private String image_url;

    @Generated
    public AllCategoryTopics() {
    }

    @Generated
    public AllCategoryTopics(String Forum_topics_id, String Forum_category_id, String Topic_name, String Created_on, String Created_by, String Total_comments, String image_url) {
        this.Forum_topics_id = Forum_topics_id;
        this.Forum_category_id = Forum_category_id;
        this.Topic_name = Topic_name;
        this.Created_on = Created_on;
        this.Created_by = Created_by;
        this.Total_comments = Total_comments;
        this.image_url = image_url;
    }

    public String getForum_topics_id() {
        return Forum_topics_id;
    }

    public void setForum_topics_id(String Forum_topics_id) {
        this.Forum_topics_id = Forum_topics_id;
    }

    public String getForum_category_id() {
        return Forum_category_id;
    }

    public void setForum_category_id(String Forum_category_id) {
        this.Forum_category_id = Forum_category_id;
    }

    public String getTopic_name() {
        return Topic_name;
    }

    public void setTopic_name(String Topic_name) {
        this.Topic_name = Topic_name;
    }

    public String getCreated_on() {
        return Created_on;
    }

    public void setCreated_on(String Created_on) {
        this.Created_on = Created_on;
    }

    public String getCreated_by() {
        return Created_by;
    }

    public void setCreated_by(String Created_by) {
        this.Created_by = Created_by;
    }

    public String getTotal_comments() {
        return Total_comments;
    }

    public void setTotal_comments(String Total_comments) {
        this.Total_comments = Total_comments;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

}
