package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALL_EVENTS".
 */
@Entity
public class AllEvents {
    private String event_id;
    private String is_student_calender;
    private String event_title;
    private String event_start;
    private String event_end;
    private String start_time;
    private String end_time;
    private String description;

    @Generated
    public AllEvents() {
    }

    @Generated
    public AllEvents(String event_id, String is_student_calender, String event_title, String event_start, String event_end, String start_time, String end_time, String description) {
        this.event_id = event_id;
        this.is_student_calender = is_student_calender;
        this.event_title = event_title;
        this.event_start = event_start;
        this.event_end = event_end;
        this.start_time = start_time;
        this.end_time = end_time;
        this.description = description;
    }

    public String getEvent_id() {
        return event_id;
    }

    public void setEvent_id(String event_id) {
        this.event_id = event_id;
    }

    public String getIs_student_calender() {
        return is_student_calender;
    }

    public void setIs_student_calender(String is_student_calender) {
        this.is_student_calender = is_student_calender;
    }

    public String getEvent_title() {
        return event_title;
    }

    public void setEvent_title(String event_title) {
        this.event_title = event_title;
    }

    public String getEvent_start() {
        return event_start;
    }

    public void setEvent_start(String event_start) {
        this.event_start = event_start;
    }

    public String getEvent_end() {
        return event_end;
    }

    public void setEvent_end(String event_end) {
        this.event_end = event_end;
    }

    public String getStart_time() {
        return start_time;
    }

    public void setStart_time(String start_time) {
        this.start_time = start_time;
    }

    public String getEnd_time() {
        return end_time;
    }

    public void setEnd_time(String end_time) {
        this.end_time = end_time;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

}
