package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALL_FORM_CATEGORY".
 */
@Entity
public class AllFormCategory {

    @Id
    private String Forum_category_id;
    private String Category_name;
    private String Created_on;
    private String Total_topics;
    private String Total_comments;

    @Generated
    public AllFormCategory() {
    }

    public AllFormCategory(String Forum_category_id) {
        this.Forum_category_id = Forum_category_id;
    }

    @Generated
    public AllFormCategory(String Forum_category_id, String Category_name, String Created_on, String Total_topics, String Total_comments) {
        this.Forum_category_id = Forum_category_id;
        this.Category_name = Category_name;
        this.Created_on = Created_on;
        this.Total_topics = Total_topics;
        this.Total_comments = Total_comments;
    }

    public String getForum_category_id() {
        return Forum_category_id;
    }

    public void setForum_category_id(String Forum_category_id) {
        this.Forum_category_id = Forum_category_id;
    }

    public String getCategory_name() {
        return Category_name;
    }

    public void setCategory_name(String Category_name) {
        this.Category_name = Category_name;
    }

    public String getCreated_on() {
        return Created_on;
    }

    public void setCreated_on(String Created_on) {
        this.Created_on = Created_on;
    }

    public String getTotal_topics() {
        return Total_topics;
    }

    public void setTotal_topics(String Total_topics) {
        this.Total_topics = Total_topics;
    }

    public String getTotal_comments() {
        return Total_comments;
    }

    public void setTotal_comments(String Total_comments) {
        this.Total_comments = Total_comments;
    }

}
