package dao_db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "ALL_LUNCH_ALLERGY_LIST".
*/
public class AllLunchAllergyListDao extends AbstractDao<AllLunchAllergyList, Void> {

    public static final String TABLENAME = "ALL_LUNCH_ALLERGY_LIST";

    /**
     * Properties of entity AllLunchAllergyList.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Allergy_name = new Property(0, String.class, "allergy_name", false, "ALLERGY_NAME");
        public final static Property Student_name = new Property(1, String.class, "student_name", false, "STUDENT_NAME");
    }


    public AllLunchAllergyListDao(DaoConfig config) {
        super(config);
    }
    
    public AllLunchAllergyListDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"ALL_LUNCH_ALLERGY_LIST\" (" + //
                "\"ALLERGY_NAME\" TEXT," + // 0: allergy_name
                "\"STUDENT_NAME\" TEXT);"); // 1: student_name
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"ALL_LUNCH_ALLERGY_LIST\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, AllLunchAllergyList entity) {
        stmt.clearBindings();
 
        String allergy_name = entity.getAllergy_name();
        if (allergy_name != null) {
            stmt.bindString(1, allergy_name);
        }
 
        String student_name = entity.getStudent_name();
        if (student_name != null) {
            stmt.bindString(2, student_name);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, AllLunchAllergyList entity) {
        stmt.clearBindings();
 
        String allergy_name = entity.getAllergy_name();
        if (allergy_name != null) {
            stmt.bindString(1, allergy_name);
        }
 
        String student_name = entity.getStudent_name();
        if (student_name != null) {
            stmt.bindString(2, student_name);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public AllLunchAllergyList readEntity(Cursor cursor, int offset) {
        AllLunchAllergyList entity = new AllLunchAllergyList( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // allergy_name
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // student_name
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, AllLunchAllergyList entity, int offset) {
        entity.setAllergy_name(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setStudent_name(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(AllLunchAllergyList entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(AllLunchAllergyList entity) {
        return null;
    }

    @Override
    public boolean hasKey(AllLunchAllergyList entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
