package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "ALL_WEEK_INTERVAL_LIST".
 */
@Entity
public class AllWeekIntervalList {
    private String week;
    private String interval;
    private String year;
    private String current_week;

    @Generated
    public AllWeekIntervalList() {
    }

    @Generated
    public AllWeekIntervalList(String week, String interval, String year, String current_week) {
        this.week = week;
        this.interval = interval;
        this.year = year;
        this.current_week = current_week;
    }

    public String getWeek() {
        return week;
    }

    public void setWeek(String week) {
        this.week = week;
    }

    public String getInterval() {
        return interval;
    }

    public void setInterval(String interval) {
        this.interval = interval;
    }

    public String getYear() {
        return year;
    }

    public void setYear(String year) {
        this.year = year;
    }

    public String getCurrent_week() {
        return current_week;
    }

    public void setCurrent_week(String current_week) {
        this.current_week = current_week;
    }

}
