package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CALENDER_DATA".
 */
@Entity
public class CalenderData {
    private String week_number;
    private String week_year;

    @Generated
    public CalenderData() {
    }

    @Generated
    public CalenderData(String week_number, String week_year) {
        this.week_number = week_number;
        this.week_year = week_year;
    }

    public String getWeek_number() {
        return week_number;
    }

    public void setWeek_number(String week_number) {
        this.week_number = week_number;
    }

    public String getWeek_year() {
        return week_year;
    }

    public void setWeek_year(String week_year) {
        this.week_year = week_year;
    }

}
