package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "CURRENT_WEEK_LUNCH".
 */
@Entity
public class CurrentWeekLunch {
    private String request_date;
    private String is_checked;
    private String Dayname;

    @Generated
    public CurrentWeekLunch() {
    }

    @Generated
    public CurrentWeekLunch(String request_date, String is_checked, String Dayname) {
        this.request_date = request_date;
        this.is_checked = is_checked;
        this.Dayname = Dayname;
    }

    public String getRequest_date() {
        return request_date;
    }

    public void setRequest_date(String request_date) {
        this.request_date = request_date;
    }

    public String getIs_checked() {
        return is_checked;
    }

    public void setIs_checked(String is_checked) {
        this.is_checked = is_checked;
    }

    public String getDayname() {
        return Dayname;
    }

    public void setDayname(String Dayname) {
        this.Dayname = Dayname;
    }

}
