package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "MENU_CATEGORY".
 */
@Entity
public class MenuCategory {
    private String menu_category_id;
    private String image_url;
    private String category_name;
    private String parent_id;
    private String total_menu_items;

    @Generated
    public MenuCategory() {
    }

    @Generated
    public MenuCategory(String menu_category_id, String image_url, String category_name, String parent_id, String total_menu_items) {
        this.menu_category_id = menu_category_id;
        this.image_url = image_url;
        this.category_name = category_name;
        this.parent_id = parent_id;
        this.total_menu_items = total_menu_items;
    }

    public String getMenu_category_id() {
        return menu_category_id;
    }

    public void setMenu_category_id(String menu_category_id) {
        this.menu_category_id = menu_category_id;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getCategory_name() {
        return category_name;
    }

    public void setCategory_name(String category_name) {
        this.category_name = category_name;
    }

    public String getParent_id() {
        return parent_id;
    }

    public void setParent_id(String parent_id) {
        this.parent_id = parent_id;
    }

    public String getTotal_menu_items() {
        return total_menu_items;
    }

    public void setTotal_menu_items(String total_menu_items) {
        this.total_menu_items = total_menu_items;
    }

}
