package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "SUBMIT_BUDGET".
 */
@Entity
public class SubmitBudget {
    private String Week_interval;
    private String Giftcardamountspend_1;
    private String credititems_1;
    private String Creditamount_1;
    private String Giftcardamountspend_2;
    private String credititems_2;
    private String Creditamount_2;
    private String Giftcardamountspend_3;
    private String credititems_3;
    private String Creditamount_3;
    private String Giftcardamountspend_4;
    private String credititems_4;
    private String Creditamount_4;
    private String Giftcardamountspend_5;
    private String credititems_5;
    private String Creditamount_5;
    private String Giftcardamountspend_6;
    private String credititems_6;
    private String Creditamount_6;
    private String Giftcardamountspend_7;
    private String credititems_7;
    private String Creditamount_7;
    private String Giftcardamountspend_8;
    private String credititems_8;
    private String Creditamount_8;
    private String submit_budget_id;
    private String Chef_id;
    private String Week_number;
    private String Year;
    private String Account_name;
    private String Weekly_budget;
    private String Grocery_store;
    private String Costco;
    private String Sysco;
    private String Other;
    private String Total;
    private String Over_under;
    private String Starting_balance;
    private String Ending_balance;
    private String Special_event;
    private String Total_invoice;
    private String Is_draft;

    @Generated
    public SubmitBudget() {
    }

    @Generated
    public SubmitBudget(String Week_interval, String Giftcardamountspend_1, String credititems_1, String Creditamount_1, String Giftcardamountspend_2, String credititems_2, String Creditamount_2, String Giftcardamountspend_3, String credititems_3, String Creditamount_3, String Giftcardamountspend_4, String credititems_4, String Creditamount_4, String Giftcardamountspend_5, String credititems_5, String Creditamount_5, String Giftcardamountspend_6, String credititems_6, String Creditamount_6, String Giftcardamountspend_7, String credititems_7, String Creditamount_7, String Giftcardamountspend_8, String credititems_8, String Creditamount_8, String submit_budget_id, String Chef_id, String Week_number, String Year, String Account_name, String Weekly_budget, String Grocery_store, String Costco, String Sysco, String Other, String Total, String Over_under, String Starting_balance, String Ending_balance, String Special_event, String Total_invoice, String Is_draft) {
        this.Week_interval = Week_interval;
        this.Giftcardamountspend_1 = Giftcardamountspend_1;
        this.credititems_1 = credititems_1;
        this.Creditamount_1 = Creditamount_1;
        this.Giftcardamountspend_2 = Giftcardamountspend_2;
        this.credititems_2 = credititems_2;
        this.Creditamount_2 = Creditamount_2;
        this.Giftcardamountspend_3 = Giftcardamountspend_3;
        this.credititems_3 = credititems_3;
        this.Creditamount_3 = Creditamount_3;
        this.Giftcardamountspend_4 = Giftcardamountspend_4;
        this.credititems_4 = credititems_4;
        this.Creditamount_4 = Creditamount_4;
        this.Giftcardamountspend_5 = Giftcardamountspend_5;
        this.credititems_5 = credititems_5;
        this.Creditamount_5 = Creditamount_5;
        this.Giftcardamountspend_6 = Giftcardamountspend_6;
        this.credititems_6 = credititems_6;
        this.Creditamount_6 = Creditamount_6;
        this.Giftcardamountspend_7 = Giftcardamountspend_7;
        this.credititems_7 = credititems_7;
        this.Creditamount_7 = Creditamount_7;
        this.Giftcardamountspend_8 = Giftcardamountspend_8;
        this.credititems_8 = credititems_8;
        this.Creditamount_8 = Creditamount_8;
        this.submit_budget_id = submit_budget_id;
        this.Chef_id = Chef_id;
        this.Week_number = Week_number;
        this.Year = Year;
        this.Account_name = Account_name;
        this.Weekly_budget = Weekly_budget;
        this.Grocery_store = Grocery_store;
        this.Costco = Costco;
        this.Sysco = Sysco;
        this.Other = Other;
        this.Total = Total;
        this.Over_under = Over_under;
        this.Starting_balance = Starting_balance;
        this.Ending_balance = Ending_balance;
        this.Special_event = Special_event;
        this.Total_invoice = Total_invoice;
        this.Is_draft = Is_draft;
    }

    public String getWeek_interval() {
        return Week_interval;
    }

    public void setWeek_interval(String Week_interval) {
        this.Week_interval = Week_interval;
    }

    public String getGiftcardamountspend_1() {
        return Giftcardamountspend_1;
    }

    public void setGiftcardamountspend_1(String Giftcardamountspend_1) {
        this.Giftcardamountspend_1 = Giftcardamountspend_1;
    }

    public String getCredititems_1() {
        return credititems_1;
    }

    public void setCredititems_1(String credititems_1) {
        this.credititems_1 = credititems_1;
    }

    public String getCreditamount_1() {
        return Creditamount_1;
    }

    public void setCreditamount_1(String Creditamount_1) {
        this.Creditamount_1 = Creditamount_1;
    }

    public String getGiftcardamountspend_2() {
        return Giftcardamountspend_2;
    }

    public void setGiftcardamountspend_2(String Giftcardamountspend_2) {
        this.Giftcardamountspend_2 = Giftcardamountspend_2;
    }

    public String getCredititems_2() {
        return credititems_2;
    }

    public void setCredititems_2(String credititems_2) {
        this.credititems_2 = credititems_2;
    }

    public String getCreditamount_2() {
        return Creditamount_2;
    }

    public void setCreditamount_2(String Creditamount_2) {
        this.Creditamount_2 = Creditamount_2;
    }

    public String getGiftcardamountspend_3() {
        return Giftcardamountspend_3;
    }

    public void setGiftcardamountspend_3(String Giftcardamountspend_3) {
        this.Giftcardamountspend_3 = Giftcardamountspend_3;
    }

    public String getCredititems_3() {
        return credititems_3;
    }

    public void setCredititems_3(String credititems_3) {
        this.credititems_3 = credititems_3;
    }

    public String getCreditamount_3() {
        return Creditamount_3;
    }

    public void setCreditamount_3(String Creditamount_3) {
        this.Creditamount_3 = Creditamount_3;
    }

    public String getGiftcardamountspend_4() {
        return Giftcardamountspend_4;
    }

    public void setGiftcardamountspend_4(String Giftcardamountspend_4) {
        this.Giftcardamountspend_4 = Giftcardamountspend_4;
    }

    public String getCredititems_4() {
        return credititems_4;
    }

    public void setCredititems_4(String credititems_4) {
        this.credititems_4 = credititems_4;
    }

    public String getCreditamount_4() {
        return Creditamount_4;
    }

    public void setCreditamount_4(String Creditamount_4) {
        this.Creditamount_4 = Creditamount_4;
    }

    public String getGiftcardamountspend_5() {
        return Giftcardamountspend_5;
    }

    public void setGiftcardamountspend_5(String Giftcardamountspend_5) {
        this.Giftcardamountspend_5 = Giftcardamountspend_5;
    }

    public String getCredititems_5() {
        return credititems_5;
    }

    public void setCredititems_5(String credititems_5) {
        this.credititems_5 = credititems_5;
    }

    public String getCreditamount_5() {
        return Creditamount_5;
    }

    public void setCreditamount_5(String Creditamount_5) {
        this.Creditamount_5 = Creditamount_5;
    }

    public String getGiftcardamountspend_6() {
        return Giftcardamountspend_6;
    }

    public void setGiftcardamountspend_6(String Giftcardamountspend_6) {
        this.Giftcardamountspend_6 = Giftcardamountspend_6;
    }

    public String getCredititems_6() {
        return credititems_6;
    }

    public void setCredititems_6(String credititems_6) {
        this.credititems_6 = credititems_6;
    }

    public String getCreditamount_6() {
        return Creditamount_6;
    }

    public void setCreditamount_6(String Creditamount_6) {
        this.Creditamount_6 = Creditamount_6;
    }

    public String getGiftcardamountspend_7() {
        return Giftcardamountspend_7;
    }

    public void setGiftcardamountspend_7(String Giftcardamountspend_7) {
        this.Giftcardamountspend_7 = Giftcardamountspend_7;
    }

    public String getCredititems_7() {
        return credititems_7;
    }

    public void setCredititems_7(String credititems_7) {
        this.credititems_7 = credititems_7;
    }

    public String getCreditamount_7() {
        return Creditamount_7;
    }

    public void setCreditamount_7(String Creditamount_7) {
        this.Creditamount_7 = Creditamount_7;
    }

    public String getGiftcardamountspend_8() {
        return Giftcardamountspend_8;
    }

    public void setGiftcardamountspend_8(String Giftcardamountspend_8) {
        this.Giftcardamountspend_8 = Giftcardamountspend_8;
    }

    public String getCredititems_8() {
        return credititems_8;
    }

    public void setCredititems_8(String credititems_8) {
        this.credititems_8 = credititems_8;
    }

    public String getCreditamount_8() {
        return Creditamount_8;
    }

    public void setCreditamount_8(String Creditamount_8) {
        this.Creditamount_8 = Creditamount_8;
    }

    public String getSubmit_budget_id() {
        return submit_budget_id;
    }

    public void setSubmit_budget_id(String submit_budget_id) {
        this.submit_budget_id = submit_budget_id;
    }

    public String getChef_id() {
        return Chef_id;
    }

    public void setChef_id(String Chef_id) {
        this.Chef_id = Chef_id;
    }

    public String getWeek_number() {
        return Week_number;
    }

    public void setWeek_number(String Week_number) {
        this.Week_number = Week_number;
    }

    public String getYear() {
        return Year;
    }

    public void setYear(String Year) {
        this.Year = Year;
    }

    public String getAccount_name() {
        return Account_name;
    }

    public void setAccount_name(String Account_name) {
        this.Account_name = Account_name;
    }

    public String getWeekly_budget() {
        return Weekly_budget;
    }

    public void setWeekly_budget(String Weekly_budget) {
        this.Weekly_budget = Weekly_budget;
    }

    public String getGrocery_store() {
        return Grocery_store;
    }

    public void setGrocery_store(String Grocery_store) {
        this.Grocery_store = Grocery_store;
    }

    public String getCostco() {
        return Costco;
    }

    public void setCostco(String Costco) {
        this.Costco = Costco;
    }

    public String getSysco() {
        return Sysco;
    }

    public void setSysco(String Sysco) {
        this.Sysco = Sysco;
    }

    public String getOther() {
        return Other;
    }

    public void setOther(String Other) {
        this.Other = Other;
    }

    public String getTotal() {
        return Total;
    }

    public void setTotal(String Total) {
        this.Total = Total;
    }

    public String getOver_under() {
        return Over_under;
    }

    public void setOver_under(String Over_under) {
        this.Over_under = Over_under;
    }

    public String getStarting_balance() {
        return Starting_balance;
    }

    public void setStarting_balance(String Starting_balance) {
        this.Starting_balance = Starting_balance;
    }

    public String getEnding_balance() {
        return Ending_balance;
    }

    public void setEnding_balance(String Ending_balance) {
        this.Ending_balance = Ending_balance;
    }

    public String getSpecial_event() {
        return Special_event;
    }

    public void setSpecial_event(String Special_event) {
        this.Special_event = Special_event;
    }

    public String getTotal_invoice() {
        return Total_invoice;
    }

    public void setTotal_invoice(String Total_invoice) {
        this.Total_invoice = Total_invoice;
    }

    public String getIs_draft() {
        return Is_draft;
    }

    public void setIs_draft(String Is_draft) {
        this.Is_draft = Is_draft;
    }

}
