package dao_db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SUBMIT_BUDGET".
*/
public class SubmitBudgetDao extends AbstractDao<SubmitBudget, Void> {

    public static final String TABLENAME = "SUBMIT_BUDGET";

    /**
     * Properties of entity SubmitBudget.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Week_interval = new Property(0, String.class, "Week_interval", false, "WEEK_INTERVAL");
        public final static Property Giftcardamountspend_1 = new Property(1, String.class, "Giftcardamountspend_1", false, "GIFTCARDAMOUNTSPEND_1");
        public final static Property Credititems_1 = new Property(2, String.class, "credititems_1", false, "CREDITITEMS_1");
        public final static Property Creditamount_1 = new Property(3, String.class, "Creditamount_1", false, "CREDITAMOUNT_1");
        public final static Property Giftcardamountspend_2 = new Property(4, String.class, "Giftcardamountspend_2", false, "GIFTCARDAMOUNTSPEND_2");
        public final static Property Credititems_2 = new Property(5, String.class, "credititems_2", false, "CREDITITEMS_2");
        public final static Property Creditamount_2 = new Property(6, String.class, "Creditamount_2", false, "CREDITAMOUNT_2");
        public final static Property Giftcardamountspend_3 = new Property(7, String.class, "Giftcardamountspend_3", false, "GIFTCARDAMOUNTSPEND_3");
        public final static Property Credititems_3 = new Property(8, String.class, "credititems_3", false, "CREDITITEMS_3");
        public final static Property Creditamount_3 = new Property(9, String.class, "Creditamount_3", false, "CREDITAMOUNT_3");
        public final static Property Giftcardamountspend_4 = new Property(10, String.class, "Giftcardamountspend_4", false, "GIFTCARDAMOUNTSPEND_4");
        public final static Property Credititems_4 = new Property(11, String.class, "credititems_4", false, "CREDITITEMS_4");
        public final static Property Creditamount_4 = new Property(12, String.class, "Creditamount_4", false, "CREDITAMOUNT_4");
        public final static Property Giftcardamountspend_5 = new Property(13, String.class, "Giftcardamountspend_5", false, "GIFTCARDAMOUNTSPEND_5");
        public final static Property Credititems_5 = new Property(14, String.class, "credititems_5", false, "CREDITITEMS_5");
        public final static Property Creditamount_5 = new Property(15, String.class, "Creditamount_5", false, "CREDITAMOUNT_5");
        public final static Property Giftcardamountspend_6 = new Property(16, String.class, "Giftcardamountspend_6", false, "GIFTCARDAMOUNTSPEND_6");
        public final static Property Credititems_6 = new Property(17, String.class, "credititems_6", false, "CREDITITEMS_6");
        public final static Property Creditamount_6 = new Property(18, String.class, "Creditamount_6", false, "CREDITAMOUNT_6");
        public final static Property Giftcardamountspend_7 = new Property(19, String.class, "Giftcardamountspend_7", false, "GIFTCARDAMOUNTSPEND_7");
        public final static Property Credititems_7 = new Property(20, String.class, "credititems_7", false, "CREDITITEMS_7");
        public final static Property Creditamount_7 = new Property(21, String.class, "Creditamount_7", false, "CREDITAMOUNT_7");
        public final static Property Giftcardamountspend_8 = new Property(22, String.class, "Giftcardamountspend_8", false, "GIFTCARDAMOUNTSPEND_8");
        public final static Property Credititems_8 = new Property(23, String.class, "credititems_8", false, "CREDITITEMS_8");
        public final static Property Creditamount_8 = new Property(24, String.class, "Creditamount_8", false, "CREDITAMOUNT_8");
        public final static Property Submit_budget_id = new Property(25, String.class, "submit_budget_id", false, "SUBMIT_BUDGET_ID");
        public final static Property Chef_id = new Property(26, String.class, "Chef_id", false, "CHEF_ID");
        public final static Property Week_number = new Property(27, String.class, "Week_number", false, "WEEK_NUMBER");
        public final static Property Year = new Property(28, String.class, "Year", false, "YEAR");
        public final static Property Account_name = new Property(29, String.class, "Account_name", false, "ACCOUNT_NAME");
        public final static Property Weekly_budget = new Property(30, String.class, "Weekly_budget", false, "WEEKLY_BUDGET");
        public final static Property Grocery_store = new Property(31, String.class, "Grocery_store", false, "GROCERY_STORE");
        public final static Property Costco = new Property(32, String.class, "Costco", false, "COSTCO");
        public final static Property Sysco = new Property(33, String.class, "Sysco", false, "SYSCO");
        public final static Property Other = new Property(34, String.class, "Other", false, "OTHER");
        public final static Property Total = new Property(35, String.class, "Total", false, "TOTAL");
        public final static Property Over_under = new Property(36, String.class, "Over_under", false, "OVER_UNDER");
        public final static Property Starting_balance = new Property(37, String.class, "Starting_balance", false, "STARTING_BALANCE");
        public final static Property Ending_balance = new Property(38, String.class, "Ending_balance", false, "ENDING_BALANCE");
        public final static Property Special_event = new Property(39, String.class, "Special_event", false, "SPECIAL_EVENT");
        public final static Property Total_invoice = new Property(40, String.class, "Total_invoice", false, "TOTAL_INVOICE");
        public final static Property Is_draft = new Property(41, String.class, "Is_draft", false, "IS_DRAFT");
    }


    public SubmitBudgetDao(DaoConfig config) {
        super(config);
    }
    
    public SubmitBudgetDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SUBMIT_BUDGET\" (" + //
                "\"WEEK_INTERVAL\" TEXT," + // 0: Week_interval
                "\"GIFTCARDAMOUNTSPEND_1\" TEXT," + // 1: Giftcardamountspend_1
                "\"CREDITITEMS_1\" TEXT," + // 2: credititems_1
                "\"CREDITAMOUNT_1\" TEXT," + // 3: Creditamount_1
                "\"GIFTCARDAMOUNTSPEND_2\" TEXT," + // 4: Giftcardamountspend_2
                "\"CREDITITEMS_2\" TEXT," + // 5: credititems_2
                "\"CREDITAMOUNT_2\" TEXT," + // 6: Creditamount_2
                "\"GIFTCARDAMOUNTSPEND_3\" TEXT," + // 7: Giftcardamountspend_3
                "\"CREDITITEMS_3\" TEXT," + // 8: credititems_3
                "\"CREDITAMOUNT_3\" TEXT," + // 9: Creditamount_3
                "\"GIFTCARDAMOUNTSPEND_4\" TEXT," + // 10: Giftcardamountspend_4
                "\"CREDITITEMS_4\" TEXT," + // 11: credititems_4
                "\"CREDITAMOUNT_4\" TEXT," + // 12: Creditamount_4
                "\"GIFTCARDAMOUNTSPEND_5\" TEXT," + // 13: Giftcardamountspend_5
                "\"CREDITITEMS_5\" TEXT," + // 14: credititems_5
                "\"CREDITAMOUNT_5\" TEXT," + // 15: Creditamount_5
                "\"GIFTCARDAMOUNTSPEND_6\" TEXT," + // 16: Giftcardamountspend_6
                "\"CREDITITEMS_6\" TEXT," + // 17: credititems_6
                "\"CREDITAMOUNT_6\" TEXT," + // 18: Creditamount_6
                "\"GIFTCARDAMOUNTSPEND_7\" TEXT," + // 19: Giftcardamountspend_7
                "\"CREDITITEMS_7\" TEXT," + // 20: credititems_7
                "\"CREDITAMOUNT_7\" TEXT," + // 21: Creditamount_7
                "\"GIFTCARDAMOUNTSPEND_8\" TEXT," + // 22: Giftcardamountspend_8
                "\"CREDITITEMS_8\" TEXT," + // 23: credititems_8
                "\"CREDITAMOUNT_8\" TEXT," + // 24: Creditamount_8
                "\"SUBMIT_BUDGET_ID\" TEXT," + // 25: submit_budget_id
                "\"CHEF_ID\" TEXT," + // 26: Chef_id
                "\"WEEK_NUMBER\" TEXT," + // 27: Week_number
                "\"YEAR\" TEXT," + // 28: Year
                "\"ACCOUNT_NAME\" TEXT," + // 29: Account_name
                "\"WEEKLY_BUDGET\" TEXT," + // 30: Weekly_budget
                "\"GROCERY_STORE\" TEXT," + // 31: Grocery_store
                "\"COSTCO\" TEXT," + // 32: Costco
                "\"SYSCO\" TEXT," + // 33: Sysco
                "\"OTHER\" TEXT," + // 34: Other
                "\"TOTAL\" TEXT," + // 35: Total
                "\"OVER_UNDER\" TEXT," + // 36: Over_under
                "\"STARTING_BALANCE\" TEXT," + // 37: Starting_balance
                "\"ENDING_BALANCE\" TEXT," + // 38: Ending_balance
                "\"SPECIAL_EVENT\" TEXT," + // 39: Special_event
                "\"TOTAL_INVOICE\" TEXT," + // 40: Total_invoice
                "\"IS_DRAFT\" TEXT);"); // 41: Is_draft
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SUBMIT_BUDGET\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, SubmitBudget entity) {
        stmt.clearBindings();
 
        String Week_interval = entity.getWeek_interval();
        if (Week_interval != null) {
            stmt.bindString(1, Week_interval);
        }
 
        String Giftcardamountspend_1 = entity.getGiftcardamountspend_1();
        if (Giftcardamountspend_1 != null) {
            stmt.bindString(2, Giftcardamountspend_1);
        }
 
        String credititems_1 = entity.getCredititems_1();
        if (credititems_1 != null) {
            stmt.bindString(3, credititems_1);
        }
 
        String Creditamount_1 = entity.getCreditamount_1();
        if (Creditamount_1 != null) {
            stmt.bindString(4, Creditamount_1);
        }
 
        String Giftcardamountspend_2 = entity.getGiftcardamountspend_2();
        if (Giftcardamountspend_2 != null) {
            stmt.bindString(5, Giftcardamountspend_2);
        }
 
        String credititems_2 = entity.getCredititems_2();
        if (credititems_2 != null) {
            stmt.bindString(6, credititems_2);
        }
 
        String Creditamount_2 = entity.getCreditamount_2();
        if (Creditamount_2 != null) {
            stmt.bindString(7, Creditamount_2);
        }
 
        String Giftcardamountspend_3 = entity.getGiftcardamountspend_3();
        if (Giftcardamountspend_3 != null) {
            stmt.bindString(8, Giftcardamountspend_3);
        }
 
        String credititems_3 = entity.getCredititems_3();
        if (credititems_3 != null) {
            stmt.bindString(9, credititems_3);
        }
 
        String Creditamount_3 = entity.getCreditamount_3();
        if (Creditamount_3 != null) {
            stmt.bindString(10, Creditamount_3);
        }
 
        String Giftcardamountspend_4 = entity.getGiftcardamountspend_4();
        if (Giftcardamountspend_4 != null) {
            stmt.bindString(11, Giftcardamountspend_4);
        }
 
        String credititems_4 = entity.getCredititems_4();
        if (credititems_4 != null) {
            stmt.bindString(12, credititems_4);
        }
 
        String Creditamount_4 = entity.getCreditamount_4();
        if (Creditamount_4 != null) {
            stmt.bindString(13, Creditamount_4);
        }
 
        String Giftcardamountspend_5 = entity.getGiftcardamountspend_5();
        if (Giftcardamountspend_5 != null) {
            stmt.bindString(14, Giftcardamountspend_5);
        }
 
        String credititems_5 = entity.getCredititems_5();
        if (credititems_5 != null) {
            stmt.bindString(15, credititems_5);
        }
 
        String Creditamount_5 = entity.getCreditamount_5();
        if (Creditamount_5 != null) {
            stmt.bindString(16, Creditamount_5);
        }
 
        String Giftcardamountspend_6 = entity.getGiftcardamountspend_6();
        if (Giftcardamountspend_6 != null) {
            stmt.bindString(17, Giftcardamountspend_6);
        }
 
        String credititems_6 = entity.getCredititems_6();
        if (credititems_6 != null) {
            stmt.bindString(18, credititems_6);
        }
 
        String Creditamount_6 = entity.getCreditamount_6();
        if (Creditamount_6 != null) {
            stmt.bindString(19, Creditamount_6);
        }
 
        String Giftcardamountspend_7 = entity.getGiftcardamountspend_7();
        if (Giftcardamountspend_7 != null) {
            stmt.bindString(20, Giftcardamountspend_7);
        }
 
        String credititems_7 = entity.getCredititems_7();
        if (credititems_7 != null) {
            stmt.bindString(21, credititems_7);
        }
 
        String Creditamount_7 = entity.getCreditamount_7();
        if (Creditamount_7 != null) {
            stmt.bindString(22, Creditamount_7);
        }
 
        String Giftcardamountspend_8 = entity.getGiftcardamountspend_8();
        if (Giftcardamountspend_8 != null) {
            stmt.bindString(23, Giftcardamountspend_8);
        }
 
        String credititems_8 = entity.getCredititems_8();
        if (credititems_8 != null) {
            stmt.bindString(24, credititems_8);
        }
 
        String Creditamount_8 = entity.getCreditamount_8();
        if (Creditamount_8 != null) {
            stmt.bindString(25, Creditamount_8);
        }
 
        String submit_budget_id = entity.getSubmit_budget_id();
        if (submit_budget_id != null) {
            stmt.bindString(26, submit_budget_id);
        }
 
        String Chef_id = entity.getChef_id();
        if (Chef_id != null) {
            stmt.bindString(27, Chef_id);
        }
 
        String Week_number = entity.getWeek_number();
        if (Week_number != null) {
            stmt.bindString(28, Week_number);
        }
 
        String Year = entity.getYear();
        if (Year != null) {
            stmt.bindString(29, Year);
        }
 
        String Account_name = entity.getAccount_name();
        if (Account_name != null) {
            stmt.bindString(30, Account_name);
        }
 
        String Weekly_budget = entity.getWeekly_budget();
        if (Weekly_budget != null) {
            stmt.bindString(31, Weekly_budget);
        }
 
        String Grocery_store = entity.getGrocery_store();
        if (Grocery_store != null) {
            stmt.bindString(32, Grocery_store);
        }
 
        String Costco = entity.getCostco();
        if (Costco != null) {
            stmt.bindString(33, Costco);
        }
 
        String Sysco = entity.getSysco();
        if (Sysco != null) {
            stmt.bindString(34, Sysco);
        }
 
        String Other = entity.getOther();
        if (Other != null) {
            stmt.bindString(35, Other);
        }
 
        String Total = entity.getTotal();
        if (Total != null) {
            stmt.bindString(36, Total);
        }
 
        String Over_under = entity.getOver_under();
        if (Over_under != null) {
            stmt.bindString(37, Over_under);
        }
 
        String Starting_balance = entity.getStarting_balance();
        if (Starting_balance != null) {
            stmt.bindString(38, Starting_balance);
        }
 
        String Ending_balance = entity.getEnding_balance();
        if (Ending_balance != null) {
            stmt.bindString(39, Ending_balance);
        }
 
        String Special_event = entity.getSpecial_event();
        if (Special_event != null) {
            stmt.bindString(40, Special_event);
        }
 
        String Total_invoice = entity.getTotal_invoice();
        if (Total_invoice != null) {
            stmt.bindString(41, Total_invoice);
        }
 
        String Is_draft = entity.getIs_draft();
        if (Is_draft != null) {
            stmt.bindString(42, Is_draft);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, SubmitBudget entity) {
        stmt.clearBindings();
 
        String Week_interval = entity.getWeek_interval();
        if (Week_interval != null) {
            stmt.bindString(1, Week_interval);
        }
 
        String Giftcardamountspend_1 = entity.getGiftcardamountspend_1();
        if (Giftcardamountspend_1 != null) {
            stmt.bindString(2, Giftcardamountspend_1);
        }
 
        String credititems_1 = entity.getCredititems_1();
        if (credititems_1 != null) {
            stmt.bindString(3, credititems_1);
        }
 
        String Creditamount_1 = entity.getCreditamount_1();
        if (Creditamount_1 != null) {
            stmt.bindString(4, Creditamount_1);
        }
 
        String Giftcardamountspend_2 = entity.getGiftcardamountspend_2();
        if (Giftcardamountspend_2 != null) {
            stmt.bindString(5, Giftcardamountspend_2);
        }
 
        String credititems_2 = entity.getCredititems_2();
        if (credititems_2 != null) {
            stmt.bindString(6, credititems_2);
        }
 
        String Creditamount_2 = entity.getCreditamount_2();
        if (Creditamount_2 != null) {
            stmt.bindString(7, Creditamount_2);
        }
 
        String Giftcardamountspend_3 = entity.getGiftcardamountspend_3();
        if (Giftcardamountspend_3 != null) {
            stmt.bindString(8, Giftcardamountspend_3);
        }
 
        String credititems_3 = entity.getCredititems_3();
        if (credititems_3 != null) {
            stmt.bindString(9, credititems_3);
        }
 
        String Creditamount_3 = entity.getCreditamount_3();
        if (Creditamount_3 != null) {
            stmt.bindString(10, Creditamount_3);
        }
 
        String Giftcardamountspend_4 = entity.getGiftcardamountspend_4();
        if (Giftcardamountspend_4 != null) {
            stmt.bindString(11, Giftcardamountspend_4);
        }
 
        String credititems_4 = entity.getCredititems_4();
        if (credititems_4 != null) {
            stmt.bindString(12, credititems_4);
        }
 
        String Creditamount_4 = entity.getCreditamount_4();
        if (Creditamount_4 != null) {
            stmt.bindString(13, Creditamount_4);
        }
 
        String Giftcardamountspend_5 = entity.getGiftcardamountspend_5();
        if (Giftcardamountspend_5 != null) {
            stmt.bindString(14, Giftcardamountspend_5);
        }
 
        String credititems_5 = entity.getCredititems_5();
        if (credititems_5 != null) {
            stmt.bindString(15, credititems_5);
        }
 
        String Creditamount_5 = entity.getCreditamount_5();
        if (Creditamount_5 != null) {
            stmt.bindString(16, Creditamount_5);
        }
 
        String Giftcardamountspend_6 = entity.getGiftcardamountspend_6();
        if (Giftcardamountspend_6 != null) {
            stmt.bindString(17, Giftcardamountspend_6);
        }
 
        String credititems_6 = entity.getCredititems_6();
        if (credititems_6 != null) {
            stmt.bindString(18, credititems_6);
        }
 
        String Creditamount_6 = entity.getCreditamount_6();
        if (Creditamount_6 != null) {
            stmt.bindString(19, Creditamount_6);
        }
 
        String Giftcardamountspend_7 = entity.getGiftcardamountspend_7();
        if (Giftcardamountspend_7 != null) {
            stmt.bindString(20, Giftcardamountspend_7);
        }
 
        String credititems_7 = entity.getCredititems_7();
        if (credititems_7 != null) {
            stmt.bindString(21, credititems_7);
        }
 
        String Creditamount_7 = entity.getCreditamount_7();
        if (Creditamount_7 != null) {
            stmt.bindString(22, Creditamount_7);
        }
 
        String Giftcardamountspend_8 = entity.getGiftcardamountspend_8();
        if (Giftcardamountspend_8 != null) {
            stmt.bindString(23, Giftcardamountspend_8);
        }
 
        String credititems_8 = entity.getCredititems_8();
        if (credititems_8 != null) {
            stmt.bindString(24, credititems_8);
        }
 
        String Creditamount_8 = entity.getCreditamount_8();
        if (Creditamount_8 != null) {
            stmt.bindString(25, Creditamount_8);
        }
 
        String submit_budget_id = entity.getSubmit_budget_id();
        if (submit_budget_id != null) {
            stmt.bindString(26, submit_budget_id);
        }
 
        String Chef_id = entity.getChef_id();
        if (Chef_id != null) {
            stmt.bindString(27, Chef_id);
        }
 
        String Week_number = entity.getWeek_number();
        if (Week_number != null) {
            stmt.bindString(28, Week_number);
        }
 
        String Year = entity.getYear();
        if (Year != null) {
            stmt.bindString(29, Year);
        }
 
        String Account_name = entity.getAccount_name();
        if (Account_name != null) {
            stmt.bindString(30, Account_name);
        }
 
        String Weekly_budget = entity.getWeekly_budget();
        if (Weekly_budget != null) {
            stmt.bindString(31, Weekly_budget);
        }
 
        String Grocery_store = entity.getGrocery_store();
        if (Grocery_store != null) {
            stmt.bindString(32, Grocery_store);
        }
 
        String Costco = entity.getCostco();
        if (Costco != null) {
            stmt.bindString(33, Costco);
        }
 
        String Sysco = entity.getSysco();
        if (Sysco != null) {
            stmt.bindString(34, Sysco);
        }
 
        String Other = entity.getOther();
        if (Other != null) {
            stmt.bindString(35, Other);
        }
 
        String Total = entity.getTotal();
        if (Total != null) {
            stmt.bindString(36, Total);
        }
 
        String Over_under = entity.getOver_under();
        if (Over_under != null) {
            stmt.bindString(37, Over_under);
        }
 
        String Starting_balance = entity.getStarting_balance();
        if (Starting_balance != null) {
            stmt.bindString(38, Starting_balance);
        }
 
        String Ending_balance = entity.getEnding_balance();
        if (Ending_balance != null) {
            stmt.bindString(39, Ending_balance);
        }
 
        String Special_event = entity.getSpecial_event();
        if (Special_event != null) {
            stmt.bindString(40, Special_event);
        }
 
        String Total_invoice = entity.getTotal_invoice();
        if (Total_invoice != null) {
            stmt.bindString(41, Total_invoice);
        }
 
        String Is_draft = entity.getIs_draft();
        if (Is_draft != null) {
            stmt.bindString(42, Is_draft);
        }
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public SubmitBudget readEntity(Cursor cursor, int offset) {
        SubmitBudget entity = new SubmitBudget( //
            cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0), // Week_interval
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // Giftcardamountspend_1
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // credititems_1
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // Creditamount_1
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // Giftcardamountspend_2
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // credititems_2
            cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6), // Creditamount_2
            cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7), // Giftcardamountspend_3
            cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8), // credititems_3
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // Creditamount_3
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // Giftcardamountspend_4
            cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11), // credititems_4
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // Creditamount_4
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // Giftcardamountspend_5
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // credititems_5
            cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15), // Creditamount_5
            cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16), // Giftcardamountspend_6
            cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17), // credititems_6
            cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18), // Creditamount_6
            cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19), // Giftcardamountspend_7
            cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20), // credititems_7
            cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21), // Creditamount_7
            cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22), // Giftcardamountspend_8
            cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23), // credititems_8
            cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24), // Creditamount_8
            cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25), // submit_budget_id
            cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26), // Chef_id
            cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27), // Week_number
            cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28), // Year
            cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29), // Account_name
            cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30), // Weekly_budget
            cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31), // Grocery_store
            cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32), // Costco
            cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33), // Sysco
            cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34), // Other
            cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35), // Total
            cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36), // Over_under
            cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37), // Starting_balance
            cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38), // Ending_balance
            cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39), // Special_event
            cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40), // Total_invoice
            cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41) // Is_draft
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, SubmitBudget entity, int offset) {
        entity.setWeek_interval(cursor.isNull(offset + 0) ? null : cursor.getString(offset + 0));
        entity.setGiftcardamountspend_1(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setCredititems_1(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCreditamount_1(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setGiftcardamountspend_2(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setCredititems_2(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setCreditamount_2(cursor.isNull(offset + 6) ? null : cursor.getString(offset + 6));
        entity.setGiftcardamountspend_3(cursor.isNull(offset + 7) ? null : cursor.getString(offset + 7));
        entity.setCredititems_3(cursor.isNull(offset + 8) ? null : cursor.getString(offset + 8));
        entity.setCreditamount_3(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setGiftcardamountspend_4(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setCredititems_4(cursor.isNull(offset + 11) ? null : cursor.getString(offset + 11));
        entity.setCreditamount_4(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setGiftcardamountspend_5(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setCredititems_5(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setCreditamount_5(cursor.isNull(offset + 15) ? null : cursor.getString(offset + 15));
        entity.setGiftcardamountspend_6(cursor.isNull(offset + 16) ? null : cursor.getString(offset + 16));
        entity.setCredititems_6(cursor.isNull(offset + 17) ? null : cursor.getString(offset + 17));
        entity.setCreditamount_6(cursor.isNull(offset + 18) ? null : cursor.getString(offset + 18));
        entity.setGiftcardamountspend_7(cursor.isNull(offset + 19) ? null : cursor.getString(offset + 19));
        entity.setCredititems_7(cursor.isNull(offset + 20) ? null : cursor.getString(offset + 20));
        entity.setCreditamount_7(cursor.isNull(offset + 21) ? null : cursor.getString(offset + 21));
        entity.setGiftcardamountspend_8(cursor.isNull(offset + 22) ? null : cursor.getString(offset + 22));
        entity.setCredititems_8(cursor.isNull(offset + 23) ? null : cursor.getString(offset + 23));
        entity.setCreditamount_8(cursor.isNull(offset + 24) ? null : cursor.getString(offset + 24));
        entity.setSubmit_budget_id(cursor.isNull(offset + 25) ? null : cursor.getString(offset + 25));
        entity.setChef_id(cursor.isNull(offset + 26) ? null : cursor.getString(offset + 26));
        entity.setWeek_number(cursor.isNull(offset + 27) ? null : cursor.getString(offset + 27));
        entity.setYear(cursor.isNull(offset + 28) ? null : cursor.getString(offset + 28));
        entity.setAccount_name(cursor.isNull(offset + 29) ? null : cursor.getString(offset + 29));
        entity.setWeekly_budget(cursor.isNull(offset + 30) ? null : cursor.getString(offset + 30));
        entity.setGrocery_store(cursor.isNull(offset + 31) ? null : cursor.getString(offset + 31));
        entity.setCostco(cursor.isNull(offset + 32) ? null : cursor.getString(offset + 32));
        entity.setSysco(cursor.isNull(offset + 33) ? null : cursor.getString(offset + 33));
        entity.setOther(cursor.isNull(offset + 34) ? null : cursor.getString(offset + 34));
        entity.setTotal(cursor.isNull(offset + 35) ? null : cursor.getString(offset + 35));
        entity.setOver_under(cursor.isNull(offset + 36) ? null : cursor.getString(offset + 36));
        entity.setStarting_balance(cursor.isNull(offset + 37) ? null : cursor.getString(offset + 37));
        entity.setEnding_balance(cursor.isNull(offset + 38) ? null : cursor.getString(offset + 38));
        entity.setSpecial_event(cursor.isNull(offset + 39) ? null : cursor.getString(offset + 39));
        entity.setTotal_invoice(cursor.isNull(offset + 40) ? null : cursor.getString(offset + 40));
        entity.setIs_draft(cursor.isNull(offset + 41) ? null : cursor.getString(offset + 41));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(SubmitBudget entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(SubmitBudget entity) {
        return null;
    }

    @Override
    public boolean hasKey(SubmitBudget entity) {
        // TODO
        return false;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
