package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TOPIC_COMMENT".
 */
@Entity
public class TopicComment {
    private String Comments_desc;
    private String Comment_created_by;
    private String Comment_created_on;
    private String comment_image_url;

    @Generated
    public TopicComment() {
    }

    @Generated
    public TopicComment(String Comments_desc, String Comment_created_by, String Comment_created_on, String comment_image_url) {
        this.Comments_desc = Comments_desc;
        this.Comment_created_by = Comment_created_by;
        this.Comment_created_on = Comment_created_on;
        this.comment_image_url = comment_image_url;
    }

    public String getComments_desc() {
        return Comments_desc;
    }

    public void setComments_desc(String Comments_desc) {
        this.Comments_desc = Comments_desc;
    }

    public String getComment_created_by() {
        return Comment_created_by;
    }

    public void setComment_created_by(String Comment_created_by) {
        this.Comment_created_by = Comment_created_by;
    }

    public String getComment_created_on() {
        return Comment_created_on;
    }

    public void setComment_created_on(String Comment_created_on) {
        this.Comment_created_on = Comment_created_on;
    }

    public String getComment_image_url() {
        return comment_image_url;
    }

    public void setComment_image_url(String comment_image_url) {
        this.comment_image_url = comment_image_url;
    }

}
