package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "TOPIC_DETAIL".
 */
@Entity
public class TopicDetail {
    private String Topic_name;
    private String Description;
    private String Topic_created_by;
    private String Topic_image_url;
    private String Topic_created_on;
    private String Total_comments;

    @Generated
    public TopicDetail() {
    }

    @Generated
    public TopicDetail(String Topic_name, String Description, String Topic_created_by, String Topic_image_url, String Topic_created_on, String Total_comments) {
        this.Topic_name = Topic_name;
        this.Description = Description;
        this.Topic_created_by = Topic_created_by;
        this.Topic_image_url = Topic_image_url;
        this.Topic_created_on = Topic_created_on;
        this.Total_comments = Total_comments;
    }

    public String getTopic_name() {
        return Topic_name;
    }

    public void setTopic_name(String Topic_name) {
        this.Topic_name = Topic_name;
    }

    public String getDescription() {
        return Description;
    }

    public void setDescription(String Description) {
        this.Description = Description;
    }

    public String getTopic_created_by() {
        return Topic_created_by;
    }

    public void setTopic_created_by(String Topic_created_by) {
        this.Topic_created_by = Topic_created_by;
    }

    public String getTopic_image_url() {
        return Topic_image_url;
    }

    public void setTopic_image_url(String Topic_image_url) {
        this.Topic_image_url = Topic_image_url;
    }

    public String getTopic_created_on() {
        return Topic_created_on;
    }

    public void setTopic_created_on(String Topic_created_on) {
        this.Topic_created_on = Topic_created_on;
    }

    public String getTotal_comments() {
        return Total_comments;
    }

    public void setTotal_comments(String Total_comments) {
        this.Total_comments = Total_comments;
    }

}
