package dao_db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "USER_LOGIN_INFO".
 */
@Entity
public class UserLoginInfo {
    private String student_id;
    private String chef_id;

    @Id
    private String user_id;
    private String user_name;
    private String first_name;
    private String last_name;
    private String email;
    private String phone;
    private String address;
    private String city;
    private String state;
    private String zip;
    private String image_url;
    private String status;
    private String session_token;
    private String house_id;
    private String house_name;
    private String campus_id;
    private String campus_name;
    private String code;
    private String chef_name;
    private String chef_image_url;
    private String is_lateplate;
    private String is_lateplate_outofhouse;

    @Generated
    public UserLoginInfo() {
    }

    public UserLoginInfo(String user_id) {
        this.user_id = user_id;
    }

    @Generated
    public UserLoginInfo(String student_id, String chef_id, String user_id, String user_name, String first_name, String last_name, String email, String phone, String address, String city, String state, String zip, String image_url, String status, String session_token, String house_id, String house_name, String campus_id, String campus_name, String code, String chef_name, String chef_image_url, String is_lateplate, String is_lateplate_outofhouse) {
        this.student_id = student_id;
        this.chef_id = chef_id;
        this.user_id = user_id;
        this.user_name = user_name;
        this.first_name = first_name;
        this.last_name = last_name;
        this.email = email;
        this.phone = phone;
        this.address = address;
        this.city = city;
        this.state = state;
        this.zip = zip;
        this.image_url = image_url;
        this.status = status;
        this.session_token = session_token;
        this.house_id = house_id;
        this.house_name = house_name;
        this.campus_id = campus_id;
        this.campus_name = campus_name;
        this.code = code;
        this.chef_name = chef_name;
        this.chef_image_url = chef_image_url;
        this.is_lateplate = is_lateplate;
        this.is_lateplate_outofhouse = is_lateplate_outofhouse;
    }

    public String getStudent_id() {
        return student_id;
    }

    public void setStudent_id(String student_id) {
        this.student_id = student_id;
    }

    public String getChef_id() {
        return chef_id;
    }

    public void setChef_id(String chef_id) {
        this.chef_id = chef_id;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getUser_name() {
        return user_name;
    }

    public void setUser_name(String user_name) {
        this.user_name = user_name;
    }

    public String getFirst_name() {
        return first_name;
    }

    public void setFirst_name(String first_name) {
        this.first_name = first_name;
    }

    public String getLast_name() {
        return last_name;
    }

    public void setLast_name(String last_name) {
        this.last_name = last_name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getImage_url() {
        return image_url;
    }

    public void setImage_url(String image_url) {
        this.image_url = image_url;
    }

    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getSession_token() {
        return session_token;
    }

    public void setSession_token(String session_token) {
        this.session_token = session_token;
    }

    public String getHouse_id() {
        return house_id;
    }

    public void setHouse_id(String house_id) {
        this.house_id = house_id;
    }

    public String getHouse_name() {
        return house_name;
    }

    public void setHouse_name(String house_name) {
        this.house_name = house_name;
    }

    public String getCampus_id() {
        return campus_id;
    }

    public void setCampus_id(String campus_id) {
        this.campus_id = campus_id;
    }

    public String getCampus_name() {
        return campus_name;
    }

    public void setCampus_name(String campus_name) {
        this.campus_name = campus_name;
    }

    public String getCode() {
        return code;
    }

    public void setCode(String code) {
        this.code = code;
    }

    public String getChef_name() {
        return chef_name;
    }

    public void setChef_name(String chef_name) {
        this.chef_name = chef_name;
    }

    public String getChef_image_url() {
        return chef_image_url;
    }

    public void setChef_image_url(String chef_image_url) {
        this.chef_image_url = chef_image_url;
    }

    public String getIs_lateplate() {
        return is_lateplate;
    }

    public void setIs_lateplate(String is_lateplate) {
        this.is_lateplate = is_lateplate;
    }

    public String getIs_lateplate_outofhouse() {
        return is_lateplate_outofhouse;
    }

    public void setIs_lateplate_outofhouse(String is_lateplate_outofhouse) {
        this.is_lateplate_outofhouse = is_lateplate_outofhouse;
    }

}
